# Generated by Django 6.0.7 on 2026-08-05 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='book',
            name='source_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='published_year',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
