# Generated by Django 6.0.7 on 2026-08-05 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_seed_book_catalog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(default='books/default-cover.png', upload_to='books/'),
        ),
    ]
