# Generated by Django 6.0.7 on 2026-08-05 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_set_toman_book_prices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.DecimalField(decimal_places=2, default=300000, max_digits=10),
        ),
    ]
